#!/usr/bin/env bash
# Generated by scripts/render-installer-usage.py from
# config/install-options.tsv. Do not edit; run that script after changing
# the manifest.
#
# The persistent options this platform's installer accepts -- the ones a
# machine remembers and --rerun replays. The manifest is what the parser
# and the rerun record already read, so a flag listed here that the
# installer does not accept, or accepted and not listed, cannot happen.
#
# Transient execution controls belong to a single invocation rather than to
# a machine's configuration, so they are not in the manifest and stay
# hand-written in platforms/macos/install.sh after this listing.

usage_persistent_options() {
  cat <<'EOF'
  --theme FLAVOUR    Catppuccin flavour: latte, frappe, macchiato, mocha
                     (default: macchiato)
  --ocaml/--no-ocaml OCaml profile (default: false)
  --containers/--no-containers
                     Podman machine profile (default: false)
  --tailscale/--no-tailscale
                     Tailscale networking profile (default: false)
  --dictation/--no-dictation
                     Local voice dictation profile (default: false)
  --defaults/--no-defaults
                     Reversible macOS defaults (default: true)
  --ai/--no-ai       AI-assisted development profile (Claude Code and Herdr)
                     (default: false)
  --codex/--no-codex AI subcomponent: Codex CLI (default: inherit)
  --firstmate/--no-firstmate
                     AI subcomponent: FirstMate toolchain (default: inherit)
  --gnhf/--no-gnhf   AI subcomponent: GNHF (default: inherit)
  --backpass/--no-backpass
                     AI subcomponent: backpass (default: inherit)
EOF
}

# The same options as the --dry-run plan shows them: each under its manifest
# summary, with the value of the variable its own argv arm records, so a line
# cannot show one option's value beside another option's label.
plan_persistent_options() {
  # shellcheck disable=SC2154 # The installer that sources this file sets them.
  printf '%-20s %s\n' \
    'Catppuccin flavour:' "$theme" \
    'OCaml profile:' "$install_ocaml" \
    'Podman machine profile:' "$install_containers" \
    'Tailscale networking profile:' "$install_tailscale" \
    'Local voice dictation profile:' "$install_dictation" \
    'Reversible macOS defaults:' "$apply_defaults" \
    'AI-assisted development profile (Claude Code and Herdr):' "$install_ai" \
    'AI subcomponent: Codex CLI:' "${ai_codex:-inherit}" \
    'AI subcomponent: FirstMate toolchain:' "${ai_firstmate:-inherit}" \
    'AI subcomponent: GNHF:' "${ai_gnhf:-inherit}" \
    'AI subcomponent: backpass:' "${ai_backpass:-inherit}"
}
