#!/usr/bin/env bash

# This file is sourced by setup-local.sh and the user-facing theme command.

catppuccin_palette() {
  local flavour="$1"

  case "$flavour" in
  latte)
    base="eff1f5" mantle="e6e9ef" crust="dce0e8" text="4c4f69"
    subtext1="5c5f77" surface0="ccd0da" surface1="bcc0cc" overlay0="9ca0b0"
    mauve="8839ef" red="d20f39" yellow="df8e1d" green="40a02b"
    blue="1e66f5" peach="fe640b" teal="179299"
    ;;
  frappe)
    base="303446" mantle="292c3c" crust="232634" text="c6d0f5"
    subtext1="b5bfe2" surface0="414559" surface1="51576d" overlay0="737994"
    mauve="ca9ee6" red="e78284" yellow="e5c890" green="a6d189"
    blue="8caaee" peach="ef9f76" teal="81c8be"
    ;;
  macchiato)
    base="24273a" mantle="1e2030" crust="181926" text="cad3f5"
    subtext1="b8c0e0" surface0="363a4f" surface1="494d64" overlay0="6e738d"
    mauve="c6a0f6" red="ed8796" yellow="eed49f" green="a6da95"
    blue="8aadf4" peach="f5a97f" teal="8bd5ca"
    ;;
  mocha)
    base="1e1e2e" mantle="181825" crust="11111b" text="cdd6f4"
    subtext1="bac2de" surface0="313244" surface1="45475a" overlay0="6c7086"
    mauve="cba6f7" red="f38ba8" yellow="f9e2af" green="a6e3a1"
    blue="89b4fa" peach="fab387" teal="94e2d5"
    ;;
  *)
    return 1
    ;;
  esac
}

write_theme_state() {
  local flavour="$1"
  local state_dir="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles"
  local wallpaper="$HOME/.local/share/wallpapers/catppuccin-${flavour}.webp"
  local lock_wallpaper="$HOME/.local/share/wallpapers/catppuccin-${flavour}-lock.webp"

  catppuccin_palette "$flavour"
  ensure_dir "$state_dir"

  printf '%s\n' "$flavour" | atomic_write_file "$state_dir/theme"
  printf 'theme = catppuccin-%s.conf\n' "$flavour" \
    | atomic_write_file "$state_dir/ghostty.conf"
  printf '[delta]\n    features = catppuccin-%s\n' "$flavour" \
    | atomic_write_file "$state_dir/git-theme"
  printf 'set -g @catppuccin_flavor "%s"\n' "$flavour" \
    | atomic_write_file "$state_dir/tmux-theme.conf"

  cat <<EOF | atomic_write_file "$state_dir/sway-theme.conf"
# Generated by the theme command. Do not edit.
set \$base #$base
set \$mantle #$mantle
set \$crust #$crust
set \$text #$text
set \$subtext1 #$subtext1
set \$surface0 #$surface0
set \$surface1 #$surface1
set \$overlay0 #$overlay0
set \$mauve #$mauve
set \$red #$red
set \$yellow #$yellow
set \$green #$green
set \$blue #$blue
set \$peach #$peach
set \$teal #$teal
set \$wallpaper $wallpaper
EOF

  cat <<EOF | atomic_write_file "$state_dir/waybar-theme.css"
/* Generated by the theme command. Do not edit. */
@define-color base #$base;
@define-color mantle #$mantle;
@define-color crust #$crust;
@define-color text #$text;
@define-color subtext1 #$subtext1;
@define-color surface0 #$surface0;
@define-color surface1 #$surface1;
@define-color overlay0 #$overlay0;
@define-color mauve #$mauve;
@define-color red #$red;
@define-color yellow #$yellow;
@define-color green #$green;
@define-color blue #$blue;
@define-color peach #$peach;
@define-color teal #$teal;
EOF

  cat <<EOF | atomic_write_file "$state_dir/fuzzel.ini"
[main]
font=monospace:size=12
terminal=ghostty
layer=overlay
width=42
lines=12
horizontal-pad=18
vertical-pad=12

[colors]
background=${base}f2
text=${text}ff
prompt=${mauve}ff
placeholder=${overlay0}ff
input=${text}ff
match=${peach}ff
selection=${surface0}ff
selection-text=${text}ff
selection-match=${peach}ff
border=${mauve}ff

[border]
width=2
radius=0
EOF

  cat <<EOF | atomic_write_file "$state_dir/mako.conf"
font=monospace 11
background-color=#$base
text-color=#$text
border-color=#$mauve
progress-color=over #$surface1
border-size=2
border-radius=0
default-timeout=7000
ignore-timeout=1
max-visible=5
layer=overlay
EOF

  cat <<EOF | atomic_write_file "$state_dir/swaylock.conf"
image=$lock_wallpaper
scaling=fill
color=$base
font=monospace
indicator-radius=90
indicator-thickness=8
inside-color=${base}ee
inside-clear-color=${yellow}ee
inside-ver-color=${blue}ee
inside-wrong-color=${red}ee
ring-color=$surface1
ring-clear-color=$yellow
ring-ver-color=$blue
ring-wrong-color=$red
key-hl-color=$mauve
bs-hl-color=$red
text-color=$text
text-clear-color=$base
text-ver-color=$base
text-wrong-color=$base
separator-color=00000000
EOF
}
