#!/usr/bin/env python3
"""Render a platform installer's persistent-option help text from its manifest.

Adding a capability to an installer means editing nine coupled places in
`platforms/<platform>/install.sh`, and two of them are prose: the `--help`
listing and the dry-run summary. Prose is where drift is invisible --- nothing
fails when a flag the parser accepts is missing from the help text, or when a
help line describes a flag that was renamed. `--tailscale/--no-tailscale` shows
both halves of it: the flag is real, its help line carries no description at
all, and `config/install-options.tsv` has had "Tailscale networking profile"
for that row the whole time.

So the listing is generated from the manifest the parser already reads. The
generated function lives in its own file rather than spliced into the usage
heredoc, because a heredoc has no comments: `# BEGIN GENERATED` inside one
would print in `--help` output. A whole generated file also means the drift gate
compares the whole file, which is the exact comparison the other eight
`render --check` gates make.

Transient execution controls --- `--dry-run`, `--non-interactive`, `--help` and
the platform's own one-run flags --- are deliberately not in that manifest, so
they stay hand-written in the installer, after the call to the generated
function.

Usage:
    scripts/render-installer-usage.py [--platform NAME] [--check]
"""

from __future__ import annotations

import pathlib
import re
import sys
import textwrap

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent / "lib"))
from generated import check_or_write  # noqa: E402
from manifests import read_tsv  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
OPTIONS = ROOT / "config" / "install-options.tsv"

# The installers whose help text is generated. A platform is added here once
# its `usage()` calls `usage_persistent_options`; until then its listing stays
# hand-written, which is visible rather than silently half-migrated.
GENERATED_PLATFORMS = ["fedora"]

# `--help` is read in a terminal, so the listing is wrapped rather than left to
# the terminal's own folding, which would break the flag column.
WIDTH = 79
# Where a summary starts, measured from the start of the line. The installers
# have used this column since the first help text; keeping it means the
# generated block sits flush with the hand-written controls below it.
SUMMARY_COLUMN = 21
INDENT = "  "


def target_for(platform: str) -> pathlib.Path:
    return ROOT / "platforms" / platform / "lib" / "usage-options.sh"


# An enumerated `values` column a reader can use as-is: lower-case words
# separated by `|`, as `latte|frappe|macchiato|mocha` and `ga402xz|ga402rk` are.
# `[4-9][0-9]|100` is a pattern for the parser to match, not a list to read, so
# it is excluded and the row states its range in the summary instead.
LITERAL_VALUES = re.compile(r"^[a-z0-9][a-z0-9.+-]*(?:\|[a-z0-9][a-z0-9.+-]*)*$")


def flag_spec(row: dict[str, str]) -> str:
    """How the option is spelled on the command line."""
    on_flag = row["on_flag"]
    off_flag = row["off_flag"]
    if row["kind"] == "value":
        return f"{on_flag} VALUE"
    if off_flag and off_flag != "-":
        return f"{on_flag}/{off_flag}"
    return on_flag


def summary_text(row: dict[str, str]) -> str:
    """The option's one-line description, with its values and its default.

    The default is stated for every option rather than only the interesting
    ones. `false` is as much a fact about the installer as `auto` is, and an
    option whose default changes in the manifest should change here without
    anybody remembering to.
    """
    parts = [row["summary"]]
    values = row["values"]
    if values and values != "-" and LITERAL_VALUES.match(values):
        parts.append(": " + ", ".join(values.split("|")))
    default = row["default"]
    if default and default != "-":
        parts.append(f" (default: {default})")
    return "".join(parts)


def render_lines(rows: list[dict[str, str]]) -> list[str]:
    """One help line per option, wrapped, with the flag column aligned."""
    specs = [(flag_spec(row), summary_text(row)) for row in rows]
    # A flag too long for the shared column gets its summary on the next line
    # rather than pushing every other summary to the right.
    column = SUMMARY_COLUMN
    lines: list[str] = []
    for spec, summary in specs:
        head = f"{INDENT}{spec}"
        wrapped = textwrap.wrap(summary, width=WIDTH - column) or [""]
        if len(head) + 1 <= column:
            lines.append(f"{head.ljust(column)}{wrapped[0]}".rstrip())
            continuation = wrapped[1:]
        else:
            lines.append(head)
            continuation = wrapped
        lines.extend(f"{' ' * column}{piece}" for piece in continuation)
    return lines


def render(platform: str, rows: list[dict[str, str]]) -> str:
    listing = render_lines(rows)
    body = [
        "#!/usr/bin/env bash",
        "# Generated by scripts/render-installer-usage.py from",
        "# config/install-options.tsv. Do not edit; run that script after changing",
        "# the manifest.",
        "#",
        "# The persistent options this platform's installer accepts -- the ones a",
        "# machine remembers and --rerun replays. The manifest is what the parser",
        "# and the rerun record already read, so a flag listed here that the",
        "# installer does not accept, or accepted and not listed, cannot happen.",
        "#",
        "# Transient execution controls belong to a single invocation rather than to",
        "# a machine's configuration, so they are not in the manifest and stay",
        f"# hand-written in platforms/{platform}/install.sh after this listing.",
        "",
        "usage_persistent_options() {",
        "  cat <<'EOF'",
        *listing,
        "EOF",
        "}",
        "",
    ]
    return "\n".join(body)


def main() -> int:
    argv = sys.argv[1:]
    platform = None
    if "--platform" in argv:
        index = argv.index("--platform")
        if index + 1 >= len(argv):
            print("--platform requires a name", file=sys.stderr)
            return 2
        platform = argv[index + 1]

    rows = read_tsv(OPTIONS)
    platforms = [platform] if platform else GENERATED_PLATFORMS
    unknown = [name for name in platforms if name not in GENERATED_PLATFORMS]
    if unknown:
        print(
            f"not a generated platform: {', '.join(unknown)}; "
            f"add it to GENERATED_PLATFORMS once its usage() calls "
            f"usage_persistent_options",
            file=sys.stderr,
        )
        return 2

    status = 0
    for name in platforms:
        platform_rows = [row for row in rows if row["platform"] == name]
        if not platform_rows:
            print(
                f"{OPTIONS} declares no options for {name}, so its help text "
                f"cannot be generated",
                file=sys.stderr,
            )
            return 1
        status |= check_or_write(
            target_for(name),
            render(name, platform_rows),
            argv,
            stale=f"Generated {name} installer help text is stale",
            remedy=f"./scripts/render-installer-usage.py --platform {name}",
        )
    return status


if __name__ == "__main__":
    raise SystemExit(main())
