#!/usr/bin/env python3
"""Render the package inventories inside docs/architecture/package-ownership.md.

That page answers *which manager owns what*. The reasoning is hand-written; the
inventories it reasons about are manifest data, and every one of them was
previously transcribed by hand. Three blocks are generated here:

* the per-platform package inventory, from `config/capabilities.tsv`;
* the mise-managed toolset, from the tracked `mise/.config/mise/config.toml`;
* the Mason inventory, from the per-profile `mason-packages.txt` files and the
  pins in `common/mason-package-versions.txt`.

`./scripts/lint.sh` runs this with `--check`, so a manifest edit that is not
reflected here fails the build instead of quietly making the page wrong.

Usage:
    scripts/render-package-ownership.py [--check]
"""

from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent / "lib"))
from manifests import mise_tools, read_tsv, supported_platforms  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
CAPABILITIES = ROOT / "config" / "capabilities.tsv"
MISE_CONFIG = ROOT / "mise" / ".config" / "mise" / "config.toml"
MASON_VERSIONS = ROOT / "common" / "mason-package-versions.txt"
TARGET = ROOT / "docs" / "architecture" / "package-ownership.md"

# Mason inventories, in the order their sections appear. The Neovim profile
# names match `nvim-lazyvim/.config/nvim/lua/config/profile.lua`.
MASON_INVENTORIES = {
    "workstation": ROOT / "nvim-lazyvim" / ".config" / "nvim" / "mason-packages.txt",
    "parrot-ctf": (
        ROOT
        / "nvim-lazyvim"
        / ".config"
        / "nvim"
        / "profiles"
        / "parrot-ctf"
        / "mason-packages.txt"
    ),
}

PLATFORM_TITLES = {
    "fedora": "Fedora workstation",
    "fedora-wsl": "Fedora on WSL",
    "macos": "Apple Silicon macOS",
    "parrot-ctf": "Parrot Security Edition CTF guest",
}
MASON_PROFILE_TITLES = {
    "workstation": "Workstation profile",
    "parrot-ctf": "Parrot CTF profile",
}

BEGIN_INVENTORY = "<!-- BEGIN GENERATED PACKAGE INVENTORY -->"
END_INVENTORY = "<!-- END GENERATED PACKAGE INVENTORY -->"
BEGIN_MISE = "<!-- BEGIN GENERATED MISE TOOLSET -->"
END_MISE = "<!-- END GENERATED MISE TOOLSET -->"
BEGIN_MASON = "<!-- BEGIN GENERATED MASON INVENTORY -->"
END_MASON = "<!-- END GENERATED MASON INVENTORY -->"

PROVENANCE = (
    "<!-- Generated by scripts/render-package-ownership.py from {sources}.\n"
    "     Do not edit between these markers; edit the manifest and regenerate. -->"
)


def capability_rows() -> list[dict[str, str]]:
    return read_tsv(CAPABILITIES)


def packages(row: dict[str, str]) -> list[str]:
    value = row["packages"]
    if value in {"", "-"}:
        return []
    return value.split(",")


def selector(row: dict[str, str]) -> str:
    """How an installation asks for this capability."""
    if row["cli_flag"] not in {"", "-"}:
        return f"`{row['cli_flag']}`"
    if row["default"] == "enabled":
        return "always"
    if row["default"] == "auto":
        return "auto-detected"
    return "—"


def render_inventory(rows: list[dict[str, str]]) -> str:
    lines = [
        BEGIN_INVENTORY,
        "",
        PROVENANCE.format(sources="config/capabilities.tsv"),
        "",
        "## Package inventory",
        "",
        "Every package this repository asks a native package manager, Homebrew or",
        "mise to install, by platform and capability. The provider column names the",
        "owner; the rest of this page explains why each owner was chosen and what it",
        "is deliberately not allowed to own. Capabilities the manifest marks",
        "unsupported on a platform install nothing there and are omitted.",
        "",
    ]

    for platform in supported_platforms():
        platform_rows = [
            row
            for row in rows
            if row["platform"] == platform
            and row["status"] == "implemented"
            and packages(row)
        ]
        if not platform_rows:
            continue
        lines.append(f"### {PLATFORM_TITLES[platform]}")
        lines.append("")
        lines.append("| Capability | Selected by | Provider | Packages |")
        lines.append("|---|---|---|---|")
        for row in sorted(platform_rows, key=lambda item: item["capability"]):
            names = " ".join(f"`{name}`" for name in sorted(packages(row)))
            lines.append(
                f"| `{row['capability']}` | {selector(row)} "
                f"| `{row['provider']}` | {names} |"
            )
        lines.append("")

    lines.append(END_INVENTORY)
    return "\n".join(lines)


def render_mise() -> str:
    tools = mise_tools(MISE_CONFIG)

    lines = [
        BEGIN_MISE,
        "",
        PROVENANCE.format(sources="mise/.config/mise/config.toml"),
        "",
        "The tracked configuration is `~/.config/mise/config.toml`, and the",
        "user-level developer toolset it declares is:",
        "",
        "| Tool | Requested version |",
        "|---|---|",
    ]
    for name, version in sorted(tools.items()):
        lines.append(f"| `{name}` | `{version}` |")
    lines.append("")
    lines.append(END_MISE)
    return "\n".join(lines)


def mason_pins() -> dict[str, str]:
    pins: dict[str, str] = {}
    for line in MASON_VERSIONS.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        package, _, version = stripped.partition(" ")
        pins[package] = version.strip()
    return pins


def mason_packages(path: pathlib.Path) -> list[str]:
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def render_mason() -> str:
    pins = mason_pins()
    sources = ", ".join(
        str(path.relative_to(ROOT)) for path in MASON_INVENTORIES.values()
    )
    lines = [
        BEGIN_MASON,
        "",
        PROVENANCE.format(sources=f"{sources} and common/mason-package-versions.txt"),
        "",
        "Mason owns the editor-facing binaries below, one inventory per Neovim",
        "profile. A package tracks whatever version its registry advertises unless",
        "the pin column names one.",
        "",
    ]
    for profile, path in MASON_INVENTORIES.items():
        names = mason_packages(path)
        lines.append(f"#### {MASON_PROFILE_TITLES[profile]}")
        lines.append("")
        lines.append(f"{len(names)} packages, from `{path.relative_to(ROOT)}`:")
        lines.append("")
        lines.append("| Mason package | Pinned version |")
        lines.append("|---|---|")
        for name in sorted(names):
            lines.append(f"| `{name}` | {f'`{pins[name]}`' if name in pins else '—'} |")
        lines.append("")
    lines.append(END_MASON)
    return "\n".join(lines)


def splice(existing: str, begin: str, end: str, generated: str) -> str:
    start = existing.find(begin)
    finish = existing.find(end)
    if start == -1 or finish == -1:
        raise SystemExit(f"{TARGET} has no {begin}/{end} markers; add them")
    return existing[:start] + generated + existing[finish + len(end) :]


def main() -> int:
    rows = capability_rows()
    existing = TARGET.read_text(encoding="utf-8")
    updated = splice(existing, BEGIN_INVENTORY, END_INVENTORY, render_inventory(rows))
    updated = splice(updated, BEGIN_MISE, END_MISE, render_mise())
    updated = splice(updated, BEGIN_MASON, END_MASON, render_mason())
    if "--check" in sys.argv:
        if existing != updated:
            print(f"Generated package ownership is stale: {TARGET}", file=sys.stderr)
            print("Run ./scripts/render-package-ownership.py", file=sys.stderr)
            return 1
        return 0
    TARGET.write_text(updated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
