#!/usr/bin/env bash
set -euo pipefail

# Generate the tracked per-flavour Starship configurations.
#
# Source of truth (issue #125):
#
#   config/starship/prompt.toml                      common prompt/modules
#   config/starship/palettes/catppuccin-<f>.toml     one palette table each
#         |
#         v
#   starship/.config/starship/catppuccin-<f>.toml    tracked, stowed output
#
# Each output therefore contains the common configuration, exactly one
# top-level `palette = 'catppuccin_<f>'` selection, and exactly one matching
# `[palettes.catppuccin_<f>]` table — never the other three flavours.
#
# Generation is deterministic and idempotent: the output is a pure function of
# the two source files, with no timestamps, hostnames or ordering that could
# differ between runs. That is what lets --check act as a CI drift gate.

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source_dir="$repo_root/config/starship"
common="$source_dir/prompt.toml"
palette_dir="$source_dir/palettes"
tracked_dir="$repo_root/starship/.config/starship"
output_dir="$tracked_dir"
check=false

flavours=(
  latte
  frappe
  macchiato
  mocha
)

usage() {
  cat <<'EOF_USAGE'
Usage: ./scripts/update-starship-themes.sh [options]

Options:
  --output-dir DIR  Write the generated files to DIR instead of the tracked
                    starship/.config/starship/
  --check           Generate into a temporary directory and byte-compare the
                    result with the tracked files. Never writes to the
                    working tree; exits non-zero and names every stale file.
  -h, --help        Show this help
EOF_USAGE
}

output_dir_explicit=false
while (($#)); do
  case "$1" in
  --output-dir)
    [[ $# -ge 2 ]] || {
      printf 'ERROR: --output-dir requires a value\n' >&2
      exit 1
    }
    output_dir="$2"
    output_dir_explicit=true
    shift 2
    ;;
  --check)
    check=true
    shift
    ;;
  -h | --help)
    usage
    exit 0
    ;;
  *)
    printf 'ERROR: Unknown option: %s\n' "$1" >&2
    usage >&2
    exit 1
    ;;
  esac
done

if [[ "$check" == true && "$output_dir_explicit" == true ]]; then
  printf 'ERROR: --check compares against the tracked files and chooses its own output directory\n' >&2
  exit 1
fi

if [[ ! -f "$common" ]]; then
  printf 'Starship prompt source not found: %s\n' "$common" >&2
  exit 1
fi

for flavour in "${flavours[@]}"; do
  palette="$palette_dir/catppuccin-${flavour}.toml"
  [[ -f "$palette" ]] || {
    printf 'Starship palette source not found: %s\n' "$palette" >&2
    exit 1
  }
  grep -Fqx "[palettes.catppuccin_${flavour}]" "$palette" || {
    printf 'Palette source does not declare [palettes.catppuccin_%s]: %s\n' \
      "$flavour" "$palette" >&2
    exit 1
  }
done

# A palette selection or table in the common source would be copied into every
# output and defeat the whole point of the split.
if grep -Eq "^palette[[:space:]]*=" "$common"; then
  printf 'Common prompt source must not select a palette: %s\n' "$common" >&2
  exit 1
fi
if grep -Eq "^\[palettes\." "$common"; then
  printf 'Common prompt source must not define a palette table: %s\n' "$common" >&2
  exit 1
fi

generate_flavour() {
  local flavour="$1" destination="$2"

  # The palette selection is a *top-level* TOML key, so it must precede the
  # first table. Emitting it after the common configuration would make it a
  # key of whichever table happens to come last, which Starship reports only
  # as a warning while silently losing the palette.
  {
    printf '# Generated by scripts/update-starship-themes.sh — do not edit.\n'
    printf '#\n'
    printf '# Sources: config/starship/prompt.toml\n'
    printf '#          config/starship/palettes/catppuccin-%s.toml\n' "$flavour"
    printf '\n'
    printf "palette = 'catppuccin_%s'\n" "$flavour"
    printf '\n'
    cat "$common"
    printf '\n'
    cat "$palette_dir/catppuccin-${flavour}.toml"
  } >"$destination"
}

if [[ "$check" == true ]]; then
  scratch="$(mktemp -d)"
  trap 'rm -rf -- "$scratch"' EXIT

  stale=()
  for flavour in "${flavours[@]}"; do
    generate_flavour "$flavour" "$scratch/catppuccin-${flavour}.toml"
    # Regenerating must be a no-op, so generation itself is compared twice.
    generate_flavour "$flavour" "$scratch/repeat-catppuccin-${flavour}.toml"
    if ! cmp -s "$scratch/catppuccin-${flavour}.toml" \
      "$scratch/repeat-catppuccin-${flavour}.toml"; then
      printf 'Generation is not deterministic for flavour: %s\n' "$flavour" >&2
      exit 1
    fi
    if ! cmp -s "$scratch/catppuccin-${flavour}.toml" \
      "$tracked_dir/catppuccin-${flavour}.toml"; then
      stale+=("starship/.config/starship/catppuccin-${flavour}.toml")
    fi
  done

  if ((${#stale[@]} > 0)); then
    printf 'Generated Starship configurations are stale:\n' >&2
    printf '  %s\n' "${stale[@]}" >&2
    printf 'Run ./scripts/update-starship-themes.sh and commit the result.\n' >&2
    exit 1
  fi

  printf 'Generated Starship configurations are current.\n'
  exit 0
fi

mkdir -p "$output_dir"

for flavour in "${flavours[@]}"; do
  generate_flavour "$flavour" "$output_dir/catppuccin-${flavour}.toml"
  printf 'Generated catppuccin-%s.toml\n' "$flavour"
done
