#!/usr/bin/env python3
"""Repository hygiene checks that are cheap, deterministic, and easy to read.

Three unrelated kinds of rot are caught here, all of which are invisible in a
diff and expensive to notice later:

1. A lone root npm lockfile. A `package-lock.json` with no root `package.json`
   is an accident: it makes dependency tooling and supply-chain scanners
   believe this repository is an npm project when nothing here runs npm.
2. A retained upstream licence text that nothing points at, or a third-party
   notice that points at a path which no longer exists.
3. A licensing page whose stated decision disagrees with what is actually in
   the repository. The check never demands that a licence be chosen: an
   undecided repository is valid. It only requires that the page and the tree
   say the same thing.
4. A reference to a repository *script* that no longer exists, in any tracked
   text file, and to a *documentation page* that no longer exists, in a script.
   Renaming one and missing a caller leaves a path that reads as real in
   documentation, in a comment, or in another script, and fails only when
   someone follows it. ShellCheck already catches a broken `source` directive;
   this catches the mentions it cannot see.
5. A tracked Python bytecode artifact. A `__pycache__` directory or a `.pyc`
   file is regenerated by the interpreter and embeds the source's mtime, so
   committing one is always an accident, not a decision.
6. A user-facing message that cites a README *section* by name. The README is
   an index of `docs/`, not the place where a profile is documented, so a
   quoted heading there is a pointer that either already rots or will: the
   citation has to name the document that actually owns the subject.
7. A workflow step that runs a third-party action at a mutable reference. A
   tag is whatever its owner last pointed it at, which is the one thing
   `docs/supply-chain.md` refuses to call a pin anywhere else.
8. A workflow whitespace check with no range. `git diff --check` alone
   inspects the working tree, which a runner always leaves clean, so the step
   reports success on exactly the damage it exists to catch.
9. A repository validation workflow that does not run the secret scanner.
   README.md claims categorically that nothing secret is in this repository,
   and `./scripts/scan-secrets.sh` is what stands behind that claim; a gate
   that can be removed by deleting one workflow step is not a gate.

Usage:
    scripts/validate-repository-hygiene.py [--root DIR]
"""

from __future__ import annotations

import argparse
import fnmatch
import pathlib
import re
import shlex
import subprocess
import sys

REFERENCE_SUFFIXES = (".sh", ".py", ".md", ".yml", ".yaml", ".tex", ".zsh", ".lua", ".toml", ".tsv")
# A path-shaped string naming one of this repository's own executable scripts.
# Deliberately narrow: runtime paths under ~/.config and documentation links
# have their own checks, and widening this only produces noise.
REPOSITORY_PATH = re.compile(
    r"(?<![\w./-])(?:common|scripts|platforms|tests)/[A-Za-z0-9_][A-Za-z0-9_./-]*\.(?:sh|py)"
)
# A documentation page named by a script. Checked only in scripts, where such a
# path is this repository telling a user where to read: in prose, the same
# shape routinely names an *upstream* project's own docs, which is exactly the
# noise the narrow rule above avoids.
DOCUMENTATION_PATH = re.compile(r"(?<![\w./-])docs/[A-Za-z0-9_][A-Za-z0-9_./-]*\.md")
SCRIPT_SUFFIXES = (".sh", ".py")
# A quoted README heading in a user-facing message: `README.md, "Something"`
# and `README.md's "Something"`. Both forms shipped in this repository's
# installer help and runtime hints, naming six headings the README no longer
# had. The fix is always the same: cite the document that owns the subject.
README_SECTION = re.compile(r"README\.md(?:,|'s)\s+[\"“]")
# Placeholders in usage text, which name a shape rather than a file.
REFERENCE_EXCEPTIONS = (
    "platforms/NAME/*",
    "platforms/PLATFORM/*",
    "platforms/<*",
)

NPM_LOCKFILES = ("package-lock.json", "npm-shrinkwrap.json", "yarn.lock", "pnpm-lock.yaml")
LICENSE_FILENAMES = ("LICENSE", "LICENSE.md", "LICENSE.txt", "LICENCE", "COPYING")
NOTICES = pathlib.Path("docs/reference/third-party-notices.md")
LICENSING = pathlib.Path("docs/reference/licensing.md")
LICENSE_TEXT_DIR = pathlib.Path("LICENSES")

WORKFLOWS = pathlib.Path(".github/workflows")
# A `uses:` step, split into the action and the reference it is pinned to, with
# whatever follows on the line. A tag or a branch is mutable: whoever can move
# it can replace the code that runs in this repository's CI, which is the same
# hazard docs/supply-chain.md refuses to accept anywhere else.
USES_STEP = re.compile(
    r"^\s*-?\s*uses:\s*(?P<action>[^@\s]+)@(?P<reference>\S+)(?P<rest>.*)$"
)
COMMIT_SHA = re.compile(r"^[0-9a-f]{40}$")
# The tag the SHA was, recorded where a reader and a bump script can both find
# it: `uses: owner/action@<sha> # v7.0.1`.
PINNED_TAG_COMMENT = re.compile(r"^\s*#\s*\S")
# `git diff --check` with nothing after it inspects the working tree, which is
# clean on every runner. Only a range compares what was committed.
WHITESPACE_CHECK = re.compile(r"git diff --check(?P<arguments>.*)$")
# Options that take no revision operand. A whitespace step spelled with one of
# these and nothing else compares two things a runner cannot tell apart:
# `--cached` compares the index to HEAD, identical after actions/checkout, and
# a lone `-- <path>` compares the working tree to the index.
NON_COMPARING_OPTIONS = frozenset({"--cached", "--staged", "--check", "--exit-code", "--quiet"})


def workflow_files(root: pathlib.Path) -> list[pathlib.Path]:
    directory = root / WORKFLOWS
    return sorted(
        path
        for suffix in ("*.yml", "*.yaml")
        for path in directory.glob(suffix)
    )

STATUS_UNDECIDED = re.compile(r"^\*\*Status: undecided\b", re.MULTILINE)
STATUS_DECIDED = re.compile(r"^\*\*Status: decided — (?P<license>[^.*]+)\.\*\*", re.MULTILINE)
MARKDOWN_LINK = re.compile(r"\[[^\]]*\]\((?P<target>[^)#\s]+)(?:#[^)\s]*)?\)")
INLINE_PATH = re.compile(r"`(?P<path>[A-Za-z0-9_.][A-Za-z0-9_./-]*/[A-Za-z0-9_./-]*)`")


def check_npm_lockfiles(root: pathlib.Path, problems: list[str]) -> None:
    manifest = root / "package.json"
    for name in NPM_LOCKFILES:
        lockfile = root / name
        if not lockfile.exists():
            continue
        if manifest.exists():
            continue
        problems.append(
            f"{name} exists at the repository root without a root package.json. "
            "This repository has no root npm project; remove the lockfile, or add "
            "the manifest, scripts and documentation that make it meaningful."
        )


def check_third_party_notices(root: pathlib.Path, problems: list[str]) -> None:
    notices = root / NOTICES
    if not notices.exists():
        problems.append(f"missing third-party notice index: {NOTICES}")
        return

    text = notices.read_text(encoding="utf-8")

    license_dir = root / LICENSE_TEXT_DIR
    retained = sorted(path.name for path in license_dir.iterdir()) if license_dir.is_dir() else []
    for name in retained:
        if f"{LICENSE_TEXT_DIR.as_posix()}/{name}" not in text:
            problems.append(
                f"{LICENSE_TEXT_DIR / name} is retained but not referenced by {NOTICES}"
            )

    for match in MARKDOWN_LINK.finditer(text):
        target = match.group("target")
        if target.startswith(("http://", "https://", "mailto:")):
            continue
        resolved = (notices.parent / target).resolve()
        if not resolved.exists():
            problems.append(f"{NOTICES} links to a path that does not exist: {target}")

    for match in INLINE_PATH.finditer(text):
        candidate = match.group("path")
        if not (root / candidate).exists():
            problems.append(
                f"{NOTICES} names a repository path that does not exist: {candidate}"
            )


def check_license_decision(root: pathlib.Path, problems: list[str]) -> None:
    licensing = root / LICENSING
    if not licensing.exists():
        problems.append(f"missing licensing decision page: {LICENSING}")
        return

    text = licensing.read_text(encoding="utf-8")
    present = [name for name in LICENSE_FILENAMES if (root / name).exists()]
    decided = STATUS_DECIDED.search(text)
    undecided = STATUS_UNDECIDED.search(text)

    if not decided and not undecided:
        problems.append(
            f"{LICENSING} must open with either '**Status: undecided' or "
            "'**Status: decided — <licence>.**' so the repository's licence state is explicit."
        )
        return

    if decided and not present:
        problems.append(
            f"{LICENSING} records the licence decision "
            f"'{decided.group('license').strip()}', but no root licence file "
            f"({', '.join(LICENSE_FILENAMES)}) exists."
        )
    if undecided and present:
        problems.append(
            f"a root licence file exists ({', '.join(present)}) but {LICENSING} still "
            "records the decision as undecided; record the chosen licence there."
        )


def check_repository_references(root: pathlib.Path, problems: list[str]) -> None:
    try:
        listing = subprocess.run(
            ["git", "-C", str(root), "ls-files", "-z"],
            check=True, capture_output=True, text=True,
        ).stdout
        names = [name for name in listing.split("\0") if name]
    except (OSError, subprocess.CalledProcessError):
        return

    tracked = set(names)
    for name in names:
        if not name.endswith(REFERENCE_SUFFIXES):
            continue
        path = root / name
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        patterns = [REPOSITORY_PATH]
        if name.endswith(SCRIPT_SUFFIXES):
            patterns.append(DOCUMENTATION_PATH)
        seen: set[str] = set()
        for match in (found for pattern in patterns for found in pattern.finditer(text)):
            reference = match.group(0)
            if reference in seen:
                continue
            seen.add(reference)
            if reference in tracked or (root / reference).exists():
                continue
            if any(fnmatch.fnmatchcase(reference, pattern) for pattern in REFERENCE_EXCEPTIONS):
                continue
            problems.append(
                f"{name}: names a repository path that does not exist: {reference}"
            )


def check_readme_sections(root: pathlib.Path, problems: list[str]) -> None:
    """No tracked shell file may cite a README section by name.

    Only shell files are checked, because this is about what an installer
    *says*: a Markdown page citing another page is an ordinary link, which
    validate-docs.py already resolves against the target's headings.
    """
    try:
        listing = subprocess.run(
            ["git", "-C", str(root), "ls-files", "-z", "--", "*.sh"],
            check=True, capture_output=True, text=True,
        ).stdout
    except (OSError, subprocess.CalledProcessError):
        return

    for name in (entry for entry in listing.split("\0") if entry):
        try:
            lines = (root / name).read_text(encoding="utf-8").splitlines()
        except (UnicodeDecodeError, OSError):
            continue
        for number, line in enumerate(lines, start=1):
            if not README_SECTION.search(line):
                continue
            problems.append(
                f"{name}:{number}: cites a README section by name: {line.strip()}. "
                "The README is an index of docs/; name the document that owns the "
                "subject instead (for example docs/profiles/ai.md)."
            )


def check_python_bytecode(root: pathlib.Path, problems: list[str]) -> None:
    try:
        listing = subprocess.run(
            ["git", "-C", str(root), "ls-files", "-z"],
            check=True, capture_output=True, text=True,
        ).stdout
        names = [name for name in listing.split("\0") if name]
    except (OSError, subprocess.CalledProcessError):
        return

    for name in names:
        if name.endswith(".pyc") or name == "__pycache__" or "/__pycache__/" in name or name.startswith("__pycache__/"):
            problems.append(
                f"{name} is a regenerated Python bytecode artifact tracked in git; "
                "remove it with `git rm --cached` and rely on the `__pycache__/`/"
                "`*.pyc` .gitignore rules instead."
            )


def check_workflow_action_pins(root: pathlib.Path, problems: list[str]) -> None:
    """Every third-party action runs at a commit this repository named.

    `actions/checkout@v7` is a tag, and a tag is whatever its owner last
    pointed it at. docs/supply-chain.md states the position -- a wildcard is
    never an exact pin -- and the workflows were the one place it was not
    applied. A local action (`./path`) is this repository's own code and needs
    no pin; a container action names an image, whose provenance belongs to
    config/network-sources.tsv.
    """
    for workflow in sorted(workflow_files(root)):
        for number, line in enumerate(workflow.read_text(encoding="utf-8").splitlines(), 1):
            match = USES_STEP.match(line)
            if not match:
                continue
            action, reference = match.group("action"), match.group("reference")
            if action.startswith((".", "docker://")):
                continue
            where = f"{workflow.relative_to(root)}:{number}"
            if not COMMIT_SHA.match(reference):
                problems.append(
                    f"{where}: {action} is pinned to {reference!r}, which is a "
                    "mutable reference. Pin it to the full 40-character commit "
                    "SHA and record the tag in a trailing comment."
                )
            elif not PINNED_TAG_COMMENT.match(match.group("rest")):
                problems.append(
                    f"{where}: {action} is pinned to a commit with no trailing "
                    "comment naming the tag it was; a bare SHA cannot be "
                    "reviewed or bumped."
                )


def names_a_commit_range(arguments: str) -> bool:
    """Does this `git diff --check` argument list name two commits to compare?

    The predicate has to be positive. Asking only whether an argument is
    present accepts `--cached` and `-- .`, which are exactly what someone
    reaches for on being told the bare form is not enough, and both compare
    something no runner can dirty.

    A range is a `..` or `...` operand, or two revisions given separately.
    Anything after a bare `--` is a pathspec, so it narrows a comparison rather
    than making one.
    """
    try:
        tokens = shlex.split(arguments)
    except ValueError:
        # An unbalanced quote is not this check's business to interpret; fall
        # back to whitespace splitting rather than accepting the line.
        tokens = arguments.split()
    if "--" in tokens:
        tokens = tokens[: tokens.index("--")]
    revisions = [
        token
        for token in tokens
        if not token.startswith("-") and token not in NON_COMPARING_OPTIONS
    ]
    if any(".." in revision for revision in revisions):
        return True
    return len(revisions) >= 2


def check_workflow_whitespace_range(root: pathlib.Path, problems: list[str]) -> None:
    """A whitespace check that compares nothing can never fail.

    `git diff --check` with no range inspects the working tree, which every
    runner leaves clean, so the step passed on committed whitespace damage that
    the ranged form in the same file caught with exit 2. `--cached` and `-- .`
    are equally vacuous for the same reason, so the predicate below requires a
    range rather than requiring an argument.
    """
    for workflow in sorted(workflow_files(root)):
        for number, line in enumerate(workflow.read_text(encoding="utf-8").splitlines(), 1):
            if line.lstrip().startswith("#"):
                continue
            match = WHITESPACE_CHECK.search(line)
            if not match or names_a_commit_range(match.group("arguments")):
                continue
            problems.append(
                f"{workflow.relative_to(root)}:{number}: `git diff --check` here "
                "names no commit range, so it inspects the working tree or the "
                "index against HEAD, both clean on a runner, and this step can "
                "never fail. Give it the range against the event's base that "
                "the other jobs use."
            )


# The scanner, and the workflow that has to run it. Matched as a command
# rather than as the word "gitleaks", so renaming the tool inside the script
# does not silently satisfy this, and so a mention in a comment does not.
SECRET_SCANNER = pathlib.Path("scripts") / "scan-secrets.sh"
SCANNER_INVOCATION = re.compile(r"(?:^|[\s;&|])\./scripts/scan-secrets\.sh(?![\w./-])")
VALIDATION_WORKFLOW = "validate.yml"


def check_secret_scanner(root: pathlib.Path, problems: list[str]) -> None:
    """The secret-scanning gate exists and the validation workflow runs it.

    README.md makes a categorical no-secret claim, and this is the only check
    that covers every tracked path and the whole history. A gate that one
    deleted workflow step disables is decorative, so the step is required
    here: removing it turns a silent loss of coverage into a lint failure.

    The script itself is required too, because a workflow line calling a file
    that does not exist would otherwise satisfy this on a tree where the gate
    had been removed outright.
    """
    if not (root / SECRET_SCANNER).is_file():
        problems.append(
            f"{SECRET_SCANNER.as_posix()} is missing, so nothing checks the "
            "README's claim that no credential is committed here."
        )
        return

    workflow = root / WORKFLOWS / VALIDATION_WORKFLOW
    if not workflow.is_file():
        problems.append(
            f"{(WORKFLOWS / VALIDATION_WORKFLOW).as_posix()} is missing, so "
            f"{SECRET_SCANNER.as_posix()} runs nowhere in CI."
        )
        return

    for line in workflow.read_text(encoding="utf-8").splitlines():
        if line.lstrip().startswith("#"):
            continue
        if SCANNER_INVOCATION.search(line):
            return

    problems.append(
        f"{(WORKFLOWS / VALIDATION_WORKFLOW).as_posix()} never runs "
        f"./{SECRET_SCANNER.as_posix()}, so a committed credential reaches "
        "main with every check green. Restore the step, or delete the "
        "README's no-secret claim along with it."
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().parents[1],
        help="repository root to check (default: this repository)",
    )
    arguments = parser.parse_args()
    root = arguments.root.resolve()

    problems: list[str] = []
    check_npm_lockfiles(root, problems)
    check_third_party_notices(root, problems)
    check_license_decision(root, problems)
    check_repository_references(root, problems)
    check_readme_sections(root, problems)
    check_python_bytecode(root, problems)
    check_workflow_action_pins(root, problems)
    check_workflow_whitespace_range(root, problems)
    check_secret_scanner(root, problems)

    for problem in problems:
        print(f"Repository hygiene: {problem}", file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
