#!/usr/bin/env bash
# Generated by scripts/render-installer-usage.py from
# config/install-options.tsv. Do not edit; run that script after changing
# the manifest.
#
# The persistent options this platform's installer accepts -- the ones a
# machine remembers and --rerun replays. The manifest is what the parser
# and the rerun record already read, so a flag listed here that the
# installer does not accept, or accepted and not listed, cannot happen.
#
# Transient execution controls belong to a single invocation rather than to
# a machine's configuration, so they are not in the manifest and stay
# hand-written in platforms/fedora/install.sh after this listing.

usage_persistent_options() {
  cat <<'EOF'
  --theme FLAVOUR    Catppuccin flavour: latte, frappe, macchiato, mocha
                     (default: macchiato)
  --kde/--no-kde     KDE integration (default: auto)
  --latex/--no-latex LaTeX toolchain (default: auto)
  --ocaml/--no-ocaml OCaml profile (default: false)
  --sway/--no-sway   Sway session (default: false)
  --vm-host          KVM/QEMU + libvirt host profile (default: false)
  --vm-guest         Explicit KVM/QEMU guest profile (default: false)
  --hardening/--no-hardening
                     Security-hardening profile (default: false)
  --desktop-tools/--no-desktop-tools
                     Desktop application profile (default: false)
  --desktop-tools-force-defaults
                     Override existing application defaults (default: false)
  --dictation/--no-dictation
                     Voice dictation profile (Handy), bound to Super+O by Sway
                     (default: false)
  --containers/--no-containers
                     Rootless Podman profile (default: false)
  --containers-api-socket
                     Rootless Podman API socket (default: false)
  --tailscale/--no-tailscale
                     Tailscale networking profile (default: false)
  --ai/--no-ai       AI-assisted development profile (Claude Code and Herdr)
                     (default: false)
  --codex/--no-codex AI subcomponent: Codex CLI (default: inherit)
  --firstmate/--no-firstmate
                     AI subcomponent: FirstMate toolchain (default: inherit)
  --gnhf/--no-gnhf   AI subcomponent: GNHF (default: inherit)
  --backpass/--no-backpass
                     AI subcomponent: backpass (default: inherit)
  --hardware MODEL   ASUS hardware model: ga402xz, ga402rk
  --secure-boot      Require Secure Boot for the selected hardware (default:
                     false)
  --charge-limit N   ASUS battery charge limit: 40-100
EOF
}
